version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/Speer-Assessment
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    privileged: true
    container_name: db
    restart: unless-stopped
    volumes:
      - ./run/setup_db.sql:/docker-entrypoint-initdb.d/01-setup_db.sql
    environment:
      - POSTGRES_USER=milan
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=speer_notes
      - POSTGRES_EXTENSIONS=pg_trgm

volumes:
  postgres_data: